// RobotBuilder Version: 2.0
//
// This file was generated by RobotBuilder. It contains sections of
// code that are automatically generated and assigned by robotbuilder.
// These sections will be updated in the future when you export to
// C++ from RobotBuilder. Do not put any code or make any change in
// the blocks indicating autogenerated code or it will be lost on an
// update. Deleting the comments indicating the section will prevent
// it from being updated in the future.


#ifndef OI_H
#define OI_H

#include "WPILib.h"

class OI {
private:
	std::shared_ptr<Joystick> copilot;
	std::shared_ptr<JoystickButton> shoot;
	std::shared_ptr<JoystickButton> climb;
	std::shared_ptr<JoystickButton> cogCollectorOpen;
	std::shared_ptr<JoystickButton> openCogCollectorDoor;
	std::shared_ptr<Joystick> driver;
	std::shared_ptr<JoystickButton> reverseOrientation;

public:
	OI();


	std::shared_ptr<Joystick> getDriver();
	std::shared_ptr<Joystick> getCopilot();

};

#endif
