// RobotBuilder Version: 2.0
//
// This file was generated by RobotBuilder. It contains sections of
// code that are automatically generated and assigned by robotbuilder.
// These sections will be updated in the future when you export to
// Java from RobotBuilder. Do not put any code or make any change in
// the blocks indicating autogenerated code or it will be lost on an
// update. Deleting the comments indicating the section will prevent
// it from being updated in the future.


package org.usfirst.frc4607.Test.subsystems;

import org.usfirst.frc4607.Test.RobotMap;
import org.usfirst.frc4607.Test.commands.*;
import edu.wpi.first.wpilibj.RobotDrive;
import edu.wpi.first.wpilibj.SpeedController;
import edu.wpi.first.wpilibj.Talon;

import edu.wpi.first.wpilibj.command.Subsystem;


/**
 *
 */
public class Climber extends Subsystem {

    private final SpeedController leftMotor = RobotMap.climberLeftMotor;



    public void initDefaultCommand() {
    	setDefaultCommand(new ClimberControl());
    }
    
    public void climb(double speed) {
    	if (Math.abs(speed) < 0.08) {
    		speed = 0.0;
    	}
    	leftMotor.set(speed);
    }
    
}

