// RobotBuilder Version: 2.0
//
// This file was generated by RobotBuilder. It contains sections of
// code that are automatically generated and assigned by robotbuilder.
// These sections will be updated in the future when you export to
// Java from RobotBuilder. Do not put any code or make any change in
// the blocks indicating autogenerated code or it will be lost on an
// update. Deleting the comments indicating the section will prevent
// it from being updated in the future.


package org.usfirst.frc4607.Test.subsystems;

import org.usfirst.frc4607.Test.RobotMap;
import org.usfirst.frc4607.Test.commands.*;
import edu.wpi.first.wpilibj.DoubleSolenoid;
import edu.wpi.first.wpilibj.Servo;

import edu.wpi.first.wpilibj.command.Subsystem;


/**
 *
 */
public class CogCollector extends Subsystem {

    private final Servo kickerServo = RobotMap.cogCollectorkickerServo;
    private final Servo linearServo = RobotMap.cogCollectorLinearServo;

    // Put methods for controlling this subsystem
    // here. Call these from Commands.
    
    
    public void openGate(){
    	linearServo.setPosition(0.75);
    }
    public void kickerOpen(){
    	kickerServo.setAngle(70);
    }
    public void kickerClose(){
    	kickerServo.setAngle(0);
    }
    
    public void closeGate(){
    	linearServo.setPosition(0.5);
    }

    public void initDefaultCommand() {
        kickerServo.setAngle(0);
        linearServo.setPosition(0.5);
    }
}

