// RobotBuilder Version: 2.0
//
// This file was generated by RobotBuilder. It contains sections of
// code that are automatically generated and assigned by robotbuilder.
// These sections will be updated in the future when you export to
// C++ from RobotBuilder. Do not put any code or make any change in
// the blocks indicating autogenerated code or it will be lost on an
// update. Deleting the comments indicating the section will prevent
// it from being updated in the future.


#include "Climber.h"
#include "../RobotMap.h"

Climber::Climber() : Subsystem("Climber") {
    rightMotor = RobotMap::climberRightMotor;
    leftMotor = RobotMap::climberLeftMotor;
    robotDrive21 = RobotMap::climberRobotDrive21;
}

// Initializes the Motor to a speed of 0 (or it starts by not running)
void Climber::InitDefaultCommand() {
	leftMotor->Set(0.0);
}

// When the operator desires to climb, the motor will reverse at a speed of 0.5
void Climber::Climb(){
	leftMotor->Set(-0.5);
}

